version: "3.1"
services:
  rdbm:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "mestre"
      MYSQL_USER: "omestre"
      MYSQL_PASSWORD: "mestre"
      MYSQL_DATABASE: "bd_omestre"
    volumes:
      - db:var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.0.4
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - rdbm

  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: "rdbm"
      WORDPRESS_DB_USER: "omestre"
      WORDPRESS_DB_PASSWORD: "mestre"
      WORDPRESS_DB_NAME: "test"
    volumes:
      - wordpress:var/www/html
    depends_on:
      - rdbm

volumes:
  db:
  wordpress:
